### PR TITLE
MS6211 pressure log with 3M mask

### PR DESCRIPTION
**Pull request by zobotek**
Log of several minutes of breathing.  98  kg male aged 60 at rest.

### CODE REVIEW

**Comment by facundo10arg** [comment]
What kind of pump did you use?

**Review by jcl5m1 — CHANGES_REQUESTED** [review]
this great, do you mind converting the log to csv?  just so we have a common format in the repository.  once you do that, i'll merge.

**Comment by zobotek** [comment]
No pump. The pressure changes are due air resistance from the filter on
inhalation and pushing open an exhalation flap valve on the way out. I'm
working on the mechanicals of an impeller pump  that can be 3D-printed.
IMO, the dynamics and mechanics of the impeller pump and motor speed
control are areas where there is significant risk of failure.  If they work
out, the SW will take some doing, but can be completed.

**Comment by facundo10arg** [comment]
Thanks for answering, my question was about the air blower specs, I can´t find anything online about that.

**Pull request merged**
