### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by axjjienn**
CAD for Universal Inline Bacterial Viral Filter for CPAP Machines

### CODE REVIEW

**Comment by RomanTheLegend** [comment]
There are few issues with your design:
1. The original part has a filter inside, so design must consist of two parts (that's the reason why I'm reworking my own)
2. Part inside is not hollow (at lease that what I see in Fusion360 cross-section analysis). Outlets - yes, they are, but main body is solid.
3. STEP format is not very Slicer-friendly - neither PrusaSlicer nor Cura want to open it
4. There are some concerns regarding double-walled design for male end - it will be 3D printed and as such, won't be as strong as the original molded part

**Comment by emilio-lopez** [comment]
I just launched this page, the Ventilators Collaboration Network (https://soptechint.com/ventilators) and am hosting webinars to help provide a communication platform for all groups working on ventilator projects to share insights and help each other. Webinars start tomorrow at 11AM US EST. There’s also a Slack channel, email newsletter, and manufacturer contacts. Would be great if your team could join!

**Comment by axjjienn** [comment]
This is the actual filter from the supplier. I created the CAD so we have it as a reference. I don't think this part should be 3D printed. This is the production viral-bacterial filter; the casings are sonically welded with the filter entrained to ensure a seal. I Use STEP because it is THE standard CAD interoperability format (as codified in ISO 10303-21), which maximizes the potential for collaboration based on this part.

**Comment by RomanTheLegend** [comment]
@axjjienn 
Regarding STEP - it's fine as long as it doesn't have to be printed. I agree that it's a standard for all CNC industry, but it requires conversion to STL in case of 3D printing. If used only as a reference model then STEP is fine.

Too late to mention, but could you please check the length of male and female inlets? In other product that I used for reference male inlet (the one with cross) is around 25.5 mm in length, and female is around 23.2  - maybe different manufacturers have slightly different designs, but just to make sure

**Comment by emilio-lopez** [comment]
Please join our upcoming webinars  https://soptechint.com/ventilators
Also, if your project isn't already in the directory, please feel free to
add it so others can understand the progress of your team and contact the
right people. Tomorrow, we'll be talking about testing of open source
ventilators.

Thanks,
Emilio

Emilio Lopez, CEO

SOP Technologies <https://soptechint.com>
emilio@soptechint.com
Phone: 305-792-8778
Social: Instagram <https://www.instagram.com/stopworldpollution/> | Facebook
<https://www.facebook.com/StopOceanPollution/> | Twitter
<https://twitter.com/fightpollution> | LinkedIn
<https://www.linkedin.com/company/stop-ocean-pollution>
1801 Coral Way, Suite 315
Miami, FL 33145

**Pull request merged**
