### PR TITLE
First Draft of resources

### PR DESCRIPTION
**Pull request by TheAmazingJarvis**

### CODE REVIEW

**Comment by peteflorence** [comment]
LGTM.

Maybe can add a link in the README.md?

**Comment by phiposurde** [comment]
cool project. I'm a critical care nurse. Here some ressource you may look at to answer some of your questions:
-A pulmonologist that (while understanding this is not an FDA approved device) is willing to advise on how to make this more effective as a last resort.***https://pulmccm.org/mechanical-ventilation-review/
-Design modifications to recapture exhaust to minimze addition viral spread. This only works in already "dirty" environments, where there is likely already airborne droplets containing virus - such as quarnateened spaces or other negative air pressure environments.
****https://www.alibaba.com/product-detail/Disposable-Ventilator-filter_926984916.html

-Solutions to prevent the system from becoming unsafe if power is lost. It's not obvious to me on how to do this. Ideas welcome.***https://www.ebay.ca/itm/Power-Gate-Battery-Backup-DC-Power-Switching-System-Power-Pole-Amateur-Ham-Radio/141351712551?hash=item20e937f727:g:0YoAAOSwqu9U59gV

to help with inspiration:https://www.youtube.com/watch?v=Y_92mDYfRGs

**Comment by PaulStefaan** [comment]
Hi, Great project !!!
I have some experience in e-health en fast prototyping and want to help...

Is it possible to get your hands on an M5stick?  or ESP, RPI zero ect to get WIFI so we can make software to talk to it and get reading... (* I can help you setup apps, api ect )

M5STICK is here my advice because of buttons and display on board.  
https://m5stack.com/products/stick-c?variant=17203451265114

I will try to make a europian version of parts you used

Also, did you look at some sensors for feedback? 
- VOC http://wiki.seeedstudio.com/Grove-VOC_and_eCO2_Gas_Sensor-SGP30/
- Pressure sensor 
- O2 meter

**Comment by RWL-69** [comment]
You may want to look at this project.  May help finance further production and research.

https://www.agorize.com/en/challenges/code-life-challenge

Robin

**Comment by MostafaAbdelmegeed** [comment]
Hello @jcl5m1 
I have assembled a team from various engineering backgrounds, we are interested in helping you with the TO-DOs, it would be nice if we could get in touch with you via Skype or Zoom.

Email me if possible:
mostafa0as3d@gmail.com

**Comment by afraniofilho** [comment]
Hi Mr. Lee, We're reproducing your project in Brazil and I'd like to duplicate your repository and translate to Portuguese to avoid misunderstanding here... We are working hard  to be prepared to face the pandemic pick in a few weeks. Do you agree? Congrats.,

**Comment by ghost** [comment]
Hello dear J. Lee

First of all i want to say Bravo !!! but above all thank you very much for sharing open source. I would like to realize your great project but i have a problem with the fan. 

I choose the alternative of using a pump to inflate only i am not 3 pinout but only the + and GND, the motor is marked "HB-166E-RoHS RS-380SH-5021VN" 

My question, is it possible used a motor with 2 +12V output cables and GND? 

Thank you so much.

(I would share the results if i manage to do your great project)
I wish you good health, peace and happiness.

**Comment by RWL-69** [comment]
Hello Col68.  

When I search for your blower, I find only the motor.  It is possible that the blower number you are using is actually just the motor part number.  Can you post a picture of the blower?

Motor speed is monitored but I think a pressure sensor could be used to monitor pressure instead of RPM.

**Comment by ghost** [comment]
Hı RWL-69

Thank you very much for your support, here are the pictures of the ventilation motor. 

<a href='https://www.casimages.com/i/200329083130396161.jpg.html' target='_blank' title='Mon image'>Mon image</a>

<a href='https://www.casimages.com/i/200329083716786984.jpg.html' target='_blank' title='Mon image'>Mon image</a>

<a href='https://www.casimages.com/i/200329083902539535.jpg.html' target='_blank' title='Mon image'>Mon image</a>

<a href='https://www.casimages.com/i/200329084008275015.jpg.html' target='_blank' title='Mon image'>Mon image</a>

I wish you happiness.

**Comment by RWL-69** [comment]
Hello Col68.

I am correct, the part number is the motor only, not the full blower. 

I cannot find the exact model number in my search but I can find the series of motors and they work off a wide variety of voltages and speeds which doesn't help in your case.

From what I have looked at in this project is that the code (third pin) is being used to calculate the pressure from the motor.  It could be used but you would have to modify the code to change the speed of the motor and control the motor due to rates and pressures.  Do you have an idea of flow rate and pressure (cm of H2O)?

It is possible but the control would need to be modified from the original project.  I will have to look at it further to give an exact answer.

**Comment by ghost** [comment]
Hi dear RWL-69

Respect for your help. I have not tested for flow and pressure (cm of H2O

The exact model is like this :
[https://www.decathlon.fr/p/pompe-electrique-rechargeable-pour-le-camping/_/R-p-134786](url)
Having seen only two output wires, i suspected that this air blower will be compatible without modification. 

Unfortunately i don't have much programming knowledge to modify. I have an L298N module (motor controller) but i have no idea how to integrate it into the project. 

I think I will try to find the ideal fan, in any case thank you very much for your support.

Respect to you.

**Comment by mauricio-porto** [comment]
Hi,

I'm trying to build this ventilator with a simple electric inflator pump.

Currently, it is able to reach a 26cm H2O (13cm heigh) at full power. Right now I'm doing a sort of stress test in order to assess its reliability.

One can see the manometer video here:

https://photos.app.goo.gl/s3gQGS5cEDV4YeMaA

Do you think its pressure and control are good enough?

**Comment by leakydata** [comment]
I found this book online for free: 'Principles and Practice of Mechanical Ventilation, 3e' https://accessmedicine.mhmedical.com/book.aspx?bookid=520 . I thought it might help, if you haven't already seen it before.

**Comment by codeavailcom** [comment]
We provide the best computer science assignment in the world with sophisticated strategies.
[https://www.codeavail.com/
](url)

**Pull request merged**
